import { Tajawal } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/HomeComponents/navbar/NavBar";
import "bootstrap/dist/css/bootstrap.min.css";
import Footer from "@/components/Footer/Footer";

const tajawal = Tajawal({
  weight: ['400', '500', '700' , '800'],
  subsets: ["arabic"],
 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={tajawal.className}>
        <NavBar />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
